//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace efConsole
{
    using System;
    using System.Collections.Generic;
    
    public partial class Folder
    {
        public Folder()
        {
            this.Files = new HashSet<File>();
            this.Folders1 = new HashSet<Folder>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public int UserId { get; set; }
        public Nullable<int> ParentFolderId { get; set; }
    
        public virtual ICollection<File> Files { get; set; }
        public virtual ICollection<Folder> Folders1 { get; set; }
        public virtual Folder Folder1 { get; set; }
    }
}
